### ISSUE TITLE
Can I revoke the permission android.permission.ACCESS_COARSE_LOCATION

### ISSUE THREAD

**Issue by ayhanasker** [DrMoriarty/godot-applovin-max#3]
Hello first of all thank you for the module.
I'm developing Android games for kids under 13 years old. Google tells me "Can I revoke the permission android.permission.ACCESS_COARSE_LOCATION" that I have to revoke this permission. Can I do this I would be glad if you help.

**Comment by DrMoriarty** [comment]
Hello @ayhanasker 
Now there are no ways to customize plugins permissions without recompilation it.
I have made for you aar without coarse location. 
[AppLovinMax.release.aar.zip](https://github.com/DrMoriarty/godot-applovin-max/files/6369097/AppLovinMax.release.aar.zip)
Just replace file in your `android/plugins` folder

**Comment by avnerh1** [comment]
> Hello @ayhanasker
> Now there are no ways to customize plugins permissions without recompilation it.
> I have made for you aar without coarse location.
> [AppLovinMax.release.aar.zip](https://github.com/DrMoriarty/godot-applovin-max/files/6369097/AppLovinMax.release.aar.zip)
> Just replace file in your `android/plugins` folder

Thank you
