### ISSUE TITLE
callback id

### ISSUE THREAD

**Issue by AbdulkarimAhmad** [DrMoriarty/godot-applovin-max#6]
Hi there 
am trying to implement the plugin in my app and i have a question  what is the callback id 

thanks

**Comment by DrMoriarty** [comment]
callback id is ad identifier of your object which should get be called.
Use it like this: `applovin_max.loadBanner("zone_id", true, get_instance_id())`

**Comment by AbdulkarimAhmad** [comment]
am sorry am kind of new at Godot why should i use it that way 
thanks

**Comment by DrMoriarty** [comment]
in gd-script you can not provide callback as you can do it in javascript, or swift, or kotlin (or other modern languages)
so native library should know the instance of your object and the name of the function which it should call.
The function names described in README also their input parameters.
The last thing is your object instance. In godot every instance of all objects has unique internal number. So when you call the method with `get_instance_id()` as a parameter, you provide the unique id of caller object.
Or you can make callback functions in other listener object. So you should call the method with `listener.get_instance_id()`

**Comment by AbdulkarimAhmad** [comment]
thank u a lot 
last question if u please 

i followed applovin max steps for add it to my project 
but in step 4 

"Enable Custom Build and check Plugins/App Lovin Max for using in Android."
its not appear neither in the plugins window or in the export window am i missing things ?
and if i rrun the game and no ads appear

**Comment by AbdulkarimAhmad** [comment]
incredible , thanks a lot every thing as u said its now appear in the export page
