### ISSUE TITLE
Error : Failed to get modified time for: com.applovin.mediation:adcolony-adapter:+.

### ISSUE THREAD

**Issue by AbdulkarimAhmad** [DrMoriarty/godot-applovin-max#7]
hi there 
i implement the plugin in my project and it start to show that error 

"Failed to get modified time for: com.applovin.mediation:adcolony-adapter:+."

i installed the applovin-adcolony from the naitvelib

**Comment by DrMoriarty** [comment]
https://github.com/godotengine/godot/issues/40871

**Comment by AbdulkarimAhmad** [comment]
so its not the reason for not showing ads right  ?

**Comment by AbdulkarimAhmad** [comment]
ads not show 

adb logcat :

`08-08 12:02:57.116 12809 12848 D AppLovinSdk: [AppLovinSdk]
08-08 12:02:57.116 12809 12848 D AppLovinSdk: ========================================
08-08 12:02:57.116 12809 12848 D AppLovinSdk: AppLovin SDK
08-08 12:02:57.116 12809 12848 D AppLovinSdk: Version: 10.0.1
08-08 12:02:57.116 12809 12848 D AppLovinSdk: Plugin Version:
08-08 12:02:57.116 12809 12848 D AppLovinSdk: Ad Review Version:
08-08 12:02:57.116 12809 12848 D AppLovinSdk: OS: N_MR1 25
08-08 12:02:57.116 12809 12848 D AppLovinSdk: Target SDK: 29
08-08 12:02:57.116 12809 12848 D AppLovinSdk: GAID: <Enable verbose logging to see the GAID to use for test devices - https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK>
08-08 12:02:57.116 12809 12848 D AppLovinSdk: SDK Key: mE1BUbDLAT33CctXIVnSB-1QBU_8TXnZhZRHQ8PmkCExPS5xTcyylWLKy-wANuH29ZzZdMA96aLmGpBvfhKqsV
08-08 12:02:57.116 12809 12848 D AppLovinSdk: Model: SM-G973F
08-08 12:02:57.116 12809 12848 D AppLovinSdk: Locale: en_US
08-08 12:02:57.116 12809 12848 D AppLovinSdk: Emulator: false
08-08 12:02:57.116 12809 12848 D AppLovinSdk: Application ID: com.pgstudios.ArabicPL2
08-08 12:02:57.116 12809 12848 D AppLovinSdk: Test Mode On: true
08-08 12:02:57.116 12809 12848 D AppLovinSdk: Verbose Logging On: false
08-08 12:02:57.116 12809 12848 D AppLovinSdk: Mediation Provider: max
08-08 12:02:57.116 12809 12848 D AppLovinSdk: TG: 48
08-08 12:02:57.116 12809 12848 D AppLovinSdk: ===Privacy States===
08-08 12:02:57.116 12809 12848 D AppLovinSdk: Please review AppLovin MAX documentation to be compliant with regional privacy policies.
08-08 12:02:57.116 12809 12848 D AppLovinSdk:
08-08 12:02:57.116 12809 12848 D AppLovinSdk: Age Restricted User - false
08-08 12:02:57.116 12809 12848 D AppLovinSdk: Has User Consent - No value set
08-08 12:02:57.116 12809 12848 D AppLovinSdk: "Do Not Sell" - false
08-08 12:02:57.116 12809 12848 D AppLovinSdk: ========================================
08-08 12:02:57.245 12809 12937 I AdColony [INFO]: Configuring AdColony
08-08 12:02:57.261 12809 12895 E PGA     : PgaUtilsParamSize: unsuported param GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS, assuming size 1
08-08 12:02:57.273 12809 12939 I ADNW_DEBUG_LOGGER: 12:02:57.269, [114c2c2b] SDK initialization started
08-08 12:02:57.343 12809 12943 I ADNW_DEBUG_LOGGER: 12:02:57.343, [35807d7e] Caching started...
08-08 12:02:57.356 12809 12809 I ADNW_DEBUG_LOGGER: 12:02:57.355, [4fbabaca] Caching complete
08-08 12:02:57.417  1519  1731 D AudioFlinger: mixer(0xb2903010) throttle end: throttle time(1)
08-08 12:02:57.418 12809 12943 I ADNW_DEBUG_LOGGER: 12:02:57.418, [114c2c2b] SDK initialization started
08-08 12:02:57.419 12809 12809 I ADNW_DEBUG_LOGGER: 12:02:57.419, [397c39bc] SDK initialization complete
08-08 12:02:57.806 12809 12913 D AppLovinSdk: [MediationDebuggerService]
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ========== MEDIATION DEBUGGER ==========
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ========== APP INFO ==========
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Dev Build - true
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Test Mode - enabled
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Target SDK - 29
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ========== MAX ==========
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK Version - 10.0.1
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Plugin Version - None
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Ad Review Version - Disabled
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ========== PRIVACY ==========
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Age Restricted User - false
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Has User Consent - No value set
08-08 12:02:57.806 12809 12913 D AppLovinSdk: "Do Not Sell" - false
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ========== NETWORKS ==========
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- ADCOLONY_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - COMPLETE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - 4.6.0
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - 4.6.0.0
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- AMAZON_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- APPLOVIN_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - COMPLETE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - 10.0.1
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - 10.0.1
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- CHARTBOOST_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: * MISSING com.google.android.gms:play-services-base: Please add "com.google.android.gms:play-services-base:x.y.z" to the dependencies block of your build.gradle
08-08 12:02:57.806 12809 12913 D AppLovinSdk: [MediationDebuggerService]
08-08 12:02:57.806 12809 12913 D AppLovinSdk:
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- FACEBOOK_MEDIATE ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - COMPLETE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - 6.5.1
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - 6.5.1.0
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- FYBER_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- GOOGLE_AD_MANAGER_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- ADMOB_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- HYPRMX_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- INMOBI_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- IRONSOURCE_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- LINE_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- MAIO_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- MINTEGRAL_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: [MediationDebuggerService]
08-08 12:02:57.806 12809 12913 D AppLovinSdk:
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- MOPUB_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- MYTARGET_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- NEND_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- OGURY_PRESAGE_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- TIKTOK_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- SMAATO_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- SNAP_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- TAPJOY_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- UNITY_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- VERIZON_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: [MediationDebuggerService]
08-08 12:02:57.806 12809 12913 D AppLovinSdk:
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- VUNGLE_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- YANDEX_NETWORK ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Status  - MISSING
08-08 12:02:57.806 12809 12913 D AppLovinSdk: SDK     - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Adapter - UNAVAILABLE
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ========== AD UNITS ==========
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ---------- First_AdUnit ----------
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Identifier - f5f830d4ff05bc6f
08-08 12:02:57.806 12809 12913 D AppLovinSdk: Format     - Banner
08-08 12:02:57.806 12809 12913 D AppLovinSdk: ========== END ==========
08-08 12:02:57.910 12809 12937 W AdColony [WARNING]: Controller : [warn] [AppConfiguration]  WARNING: TEST MODE ENABLED. PLEASE ENSURE THIS OPTION IS NOT SET IN PRODUCTION.
08-08 12:02:58.036  1529  1529 D bstfolderd: Exported Folders not mounted yet...
08-08 12:02:58.036  1529  1529 D bstfolderd: Preparing windows folder
08-08 12:02:58.036  1529  1529 I bstfolderd: Mounting volume Documents on /mnt/windows/Documents
08-08 12:02:58.037  1529  1529 E bstfolderd: MOUNT COMMAND_FAILED: Cannot mount Documents on /mnt/windows/Documents: Protocol error (71)
08-08 12:02:58.037  1529  1529 E bstfolderd: Error in mounting volume Documents
08-08 12:02:58.037  1529  1529 E bstfolderd: Caught an exception or error while mounting volume Documents
08-08 12:02:58.105 12809 12814 I art     : Do partial code cache collection, code=30KB, data=29KB
08-08 12:02:58.105 12809 12814 I art     : After code cache collection, code=30KB, data=29KB
08-08 12:02:58.105 12809 12814 I art     : Increasing code cache capacity to 128KB
08-08 12:02:58.200 12809 12850 W AppLovinSdk: [AppLovinSdk] Current SDK version (10.0.1) is outdated. Please integrate the latest version of the AppLovin SDK (10.3.2). Doing so will improve your CPMs and ensure you have access to the latest revenue earning features.
08-08 12:02:59.893 12809 12945 I ADNW_DEBUG_LOGGER: 12:02:59.893, [4e0710c5] Session data initialized`



my code : 
`	applovin_max.loadBanner("a92e65881c8b991e",true , self.get_instance_id())
	applovin_max.showBanner("a92e65881c8b991e") `

**Comment by DrMoriarty** [comment]
when do you call `showBanner` function?
you should call it inside your callback function (after loadBanner will return your success result)

**Comment by AbdulkarimAhmad** [comment]
i call it after call the `loadBanner` i use it like i used to use admob ?
am sorry i dont understand that callback function 
i used  self.get_instance_id() how can i get the call back from that

**Comment by DrMoriarty** [comment]
Ok, if you write code inside a node script:
```
func _on_pressed_some_button():
  applovin_max.loadBanner("zone", true, get_instance_id())

func _on_banner_loaded(id: String):
  # this is a callback function which will be called when the banner actually loaded
  applovin_max.showBanner(id)
```

**Comment by AbdulkarimAhmad** [comment]
hi there 
thanks a lot 
that was helpful 

i have been trying to solve error 204 and now it gone but  it show new error with errorCode 1008

```
..Reason: [{"code":1008,"msg":"Ad unit info must include the adunit ID - please double-check that your package 
name \/ bundle id matches the one defined in the MAX Ad Unit ID being used"}]

```
any Idea why it says that also i checked the package name 
the game in applovin site in application have the same package name as the game in my phone .

**Comment by DrMoriarty** [comment]
may be you have a typo in ad unit id? or some times ad unit start work after some delay (if you just created ad unit it may take some time before it will be recognized by system)

**Comment by AbdulkarimAhmad** [comment]
hi there 
thanks a lot its work now i used the id for the ad unit instead of zoneID

```
func _on_pressed_some_button():
  applovin_max.loadBanner("Ad_Unit_ID", true, get_instance_id())
```

**Comment by AbdulkarimAhmad** [comment]
hi there 
i think i know what happen 
well i found the zone id in the applovin page but am using applovin- max and it have ad unit id 
so when i use it insted of zoneid its work fine 
now i have the banner and ther rewarded ad work 
thanks a lot
